language: node_js
sudo: false
node_js:
  - '8'
services:
  - redis-server
env:
  - CXX=g++-4.8
addons:
  postgresql: '9.3'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: clifton.cunningham@tes.co.uk
  api_key:
    secure: UbkeChF4rrx+OvLFkgckIn1j5RNcNAP04TEb0ryQ3CissQ5UaKjthkfZ/UR6HiAINgoyBJgWvRJLtLvp3jgD76wyA7gu176Nqg2EeWgXcdeRx3/2m4IAZRGLHKWmdz3kEKGr+D9yjrqy2ClsurynMF0VQ2vdE6jqumHEpo+zcpk=
  on:
    tags: true  