language: node_js
sudo: false
node_js:
  - '8'
services:
  - redis-server
env:
  - CXX=g++-4.8
addons:
  postgresql: '9.3'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: clifton.cunningham@tes.co.uk
  api_key: $NPM_TOKEN
  on:
    tags: true  